apiVersion: v1
kind: Secret
metadata:
  name: graphex-secrets
  namespace: graphex-staging
type: Opaque
# echo -n "root" | base64
# echo -n "example" | base64
data:
  mongo-initdb-root-password: ZXhhbXBsZQ==
  mongo-initdb-root-username: cm9vdA==
  bearer-token: QUFBQUFBQUFBQUFBQUFBQUFBQUFBRnZabFFFQUFBQUFLSjJhTExZWVBGU1F5UnNQZ3dTb25EQUNlVDAlM0R3SmpLNjNFeXMwaXhWSHhUYVlqVHM5ZUJnT0lPckRrT0t5dEtjaXh0MW00V1gzWDRZaQ==
  reddit-username: Q29tcGxleF9Xb3JyeTI4MzM=
  reddit-password: WGE5OWJ1OTRFdTZn
  reddit-client-id: SWVUaXlKbkozdEUxbnRDSXowZGN5dw==
  reddit-secret-token: Unp0dGVqY281TURodF9GcENXSlp4VXZfQ015RnR3
  openai-api-key: c2stNnZPY295VVlwdmhCeE83cGtSTDBUM0JsYmtGSk9WT0N6TTRoZmNpdm1uWDlUZU5v

#comment for triggering rebuild